version: 2
updates:
  # Memantau dependencies Frontend (NPM)
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "daily"
    assignees:
      - "gilangabdian"

  # Memantau dependencies Backend (Composer)
  - package-ecosystem: "composer"
    directory: "/backend"
    schedule:
      interval: "daily"
    assignees:
      - "gilangabdian"
