"use client";

import React, { useState, useEffect, useRef, useCallback } from "react";
import { createPortal } from "react-dom";
import { gsap } from "gsap";
import { getVisitorMarkCount, leaveVisitorMark } from "@/lib/api/visitor";
import { Heart } from "lucide-react";

const Tooltip = ({ id, onRemove }: { id: number; onRemove: (id: number) => void }) => {
  const [isLeaving, setIsLeaving] = useState(false);

  useEffect(() => {
    const leaveTimer = setTimeout(() => {
      setIsLeaving(true);
    }, 2500);

    const removeTimer = setTimeout(() => {
      onRemove(id);
    }, 3000);

    return () => {
      clearTimeout(leaveTimer);
      clearTimeout(removeTimer);
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  return (
    <div
      className={`fixed bottom-4 right-4 bg-black text-white dark:bg-white dark:text-black px-3 py-1.5 rounded-lg shadow-lg text-xs font-medium tracking-wide font-[Inter] flex items-center gap-1.5 border border-white/10 dark:border-black/10 transition-all duration-500 ease-[cubic-bezier(0.23,1,0.32,1)] z-50 ${
        isLeaving ? "opacity-0 translate-y-4" : "animate-in fade-in slide-in-from-bottom-4"
      }`}>
      <span>Thank you!</span>
      {/* <span className="text-sm">✨</span> */}
    </div>
  );
};

export default function LeaveMark() {
  const [markCount, setMarkCount] = useState<number | null>(null);
  const [alreadyMarked, setAlreadyMarked] = useState<boolean>(false);
  const [tooltips, setTooltips] = useState<{ id: number }[]>([]);
  const [deviceId, setDeviceId] = useState<string | null>(null);
  const [isHovered, setIsHovered] = useState(false);
  const [showNumberTemporary, setShowNumberTemporary] = useState(false);
  const [heartColor, setHeartColor] = useState("#f87171"); // Default soft red

  const countRef = useRef<HTMLSpanElement>(null);
  const prevCountRef = useRef<number | null>(null);

  useEffect(() => {
    if (countRef.current && markCount !== prevCountRef.current && prevCountRef.current !== null) {
      gsap.fromTo(countRef.current, { y: 15, opacity: 0 }, { y: 0, opacity: 1, duration: 0.5, ease: "back.out(2)" });
    }
    prevCountRef.current = markCount;
  }, [markCount]);

  useEffect(() => {
    // Wait for device_id to be generated by FingerprintJS in HomepageClient
    const interval = setInterval(() => {
      const id = localStorage.getItem("device_id");
      if (id) {
        setDeviceId(id);
        clearInterval(interval);
      }
    }, 500);

    return () => clearInterval(interval);
  }, []);

  useEffect(() => {
    if (deviceId) {
      getVisitorMarkCount(deviceId)
        .then((res) => res.json())
        .then((data) => {
          if (data.data) {
            setMarkCount(data.data.total_marks);
            setAlreadyMarked(data.data.already_marked);
          }
        })
        .catch((err) => console.error("Failed to fetch mark count", err));
    } else {
      // Fetch initial count without device_id just to show the number quickly
      getVisitorMarkCount()
        .then((res) => res.json())
        .then((data) => {
          if (data.data && markCount === null) {
            setMarkCount(data.data.total_marks);
          }
        })
        .catch((err) => console.error("Failed to fetch mark count", err));
    }
  }, [deviceId]);

  const removeTooltip = React.useCallback((id: number) => {
    setTooltips((prev) => prev.filter((item) => item.id !== id));
  }, []);

  const handleLeaveMark = async () => {
    if (!deviceId) return;

    // Tambah tooltip ke array dengan ID unik
    const newId = Date.now() + Math.random();
    setTooltips((prev) => [...prev, { id: newId }]);

    if (alreadyMarked) {
      // Generate a random vibrant HSL color
      const h = Math.floor(Math.random() * 360);
      const s = Math.floor(Math.random() * 30) + 70; // 70-100% saturation
      const l = Math.floor(Math.random() * 10) + 50; // 50-60% lightness
      setHeartColor(`hsl(${h}, ${s}%, ${l}%)`);
      return; // Don't send request if already marked
    }

    // Show temporary number on click
    setShowNumberTemporary(true);

    // Hide temporary number after 4 seconds
    setTimeout(() => {
      setShowNumberTemporary(false);
    }, 4000);

    try {
      const res = await leaveVisitorMark(deviceId);
      const data = await res.json();

      if (res.ok && data.data) {
        setMarkCount(data.data.total_marks);
        setAlreadyMarked(true);
      }
    } catch (err) {
      console.error("Failed to leave mark", err);
    }
  };

  const isNumberVisible = (alreadyMarked && isHovered) || showNumberTemporary;

  return (
    <div className="relative w-full flex justify-start py-2 font-[Inter] z-20">
      <button
        onClick={handleLeaveMark}
        onMouseEnter={() => setIsHovered(true)}
        onMouseLeave={() => setIsHovered(false)}
        className="group flex flex-col items-center gap-0.5 text-neutral-400 hover:text-black dark:text-neutral-500 dark:hover:text-white transition-colors duration-300 relative cursor-pointer">
        <span className="text-xs tracking-wider font-medium opacity-70 group-hover:opacity-100 transition-opacity">
          Leave a mark
        </span>
        <div
          className={`absolute top-full left-1/2 -translate-x-1/2 overflow-hidden transition-all duration-500 ease-[cubic-bezier(0.23,1,0.32,1)] ${
            isNumberVisible ? "max-h-5 opacity-100 pt-0.5" : "max-h-0 opacity-0 pt-0"
          }`}>
          <div className="h-5 flex items-center justify-center gap-1.5">
            <Heart
              className="w-3.5 h-3.5 transition-colors duration-300"
              style={{ color: heartColor }}
              fill="currentColor"
            />
            <span ref={countRef} className="text-sm font-bold block">
              {markCount !== null ? markCount : "..."}
            </span>
          </div>
        </div>
      </button>

      {typeof document !== "undefined" &&
        tooltips.length > 0 &&
        createPortal(
          <>
            {tooltips.map((t) => (
              <Tooltip key={t.id} id={t.id} onRemove={removeTooltip} />
            ))}
          </>,
          document.body,
        )}
    </div>
  );
}
